entry: gh-start
executions: []
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: -10
      y: -310
    settings:
      folded: false
  - id: gh-checkout
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 410
      y: -70
    inputs:
      fetch-depth: '0'
    settings:
      folded: false
registries: []
description: ''
