name: Automated Git Bisect

on:
  workflow_dispatch:
    inputs:
      gh_token:
        description: 'GitHub Token for cloning and accessing the repository'
        required: false
      org_repo:
        description: 'Organization and repository name (e.g., org/repo)'
        default: "SweetRainGarden/SrgGitRecordsRepo"
        required: true
      init_branch_name:
        description: 'Initial branch name to start the bisect process'
        default: "develop"
        required: true
      good_commit:
        description: 'Known good commit'
        default: "c7e772928a6b222f1b34126cf1e586ffa98a923e"
        required: true
      bad_commit:
        description: 'Known bad commit (optional, defaults to the latest commit of the init branch)'
        default: "3a97867dcfd0f0e74980f25e6fbc1c41a5c9075a"
        required: false
      check_commands:
        default: "./gradlew test"
        description: 'Commands to test each commit, separated by newline characters'
        required: true
      java_version:
        description: 'Java version to use for the build'
        required: false
        default: '17'

jobs:
  bisect:
    runs-on: [ 'self-hosted', 'macOS' ]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4.1.1
      with:
        repository: ${{ github.event.inputs.org_repo }}
        token: ${{ secrets.GITHUB_TOKEN || github.event.inputs.gh_token }}
        ref: ${{ github.event.inputs.init_branch_name }}
        fetch-depth: '0'

    - name: "EEE -> Set build env --> 1: JDK 17"
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '${{ github.event.inputs.java_version }}'
        distribution: 'temurin'

    - name: "EEE -> Set build env --> 2: Gradle current stable version"
      uses: gradle/gradle-build-action@v3.1.0
      with:
        gradle-version: current

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3.2.0


    - name: Resolve bad commit
      run: |
        if [[ -z "${{ github.event.inputs.bad_commit }}" ]]; then
          INIT_BAD_COMMIT_ID=$(git rev-parse HEAD)
        elif git rev-parse --verify --quiet ${{ github.event.inputs.bad_commit }}^{commit}; then
          INIT_BAD_COMMIT_ID=${{ github.event.inputs.bad_commit }}
        else
          echo "The specified bad commit is invalid."
          exit 1
        fi
        echo "INIT_BAD_COMMIT_ID=$INIT_BAD_COMMIT_ID" >> $GITHUB_ENV

    - name: Create the check script
      run: |
        # first bad commit:7abdb50f6b661a3e9039c3d4d315600da7b2729e
        echo "${{ github.event.inputs.check_commands }}" > bisect-check.sh
        chmod +x bisect-check.sh

    - name: Run bisect with check command bash
      run: |
        git bisect start
        git bisect bad $INIT_BAD_COMMIT_ID
        git bisect good ${{ github.event.inputs.good_commit }}
        BISECT_OUTPUT=$(git bisect run ./bisect-check.sh)
        echo "$BISECT_OUTPUT"
        FIRST_BAD_COMMIT=$(git rev-parse bisect/bad)
        
        if [[ -z "$FIRST_BAD_COMMIT" ]]; then
          echo "No bad commit found."
        else
          echo "## Bisect result" >> $GITHUB_STEP_SUMMARY
          DIFF_URL="https://github.com/${{ github.event.inputs.org_repo }}/commit/$FIRST_BAD_COMMIT"
          echo "FIRST_BAD_COMMIT=$FIRST_BAD_COMMIT" >> $GITHUB_ENV
          echo "FIRST_BAD_COMMIT=[$FIRST_BAD_COMMIT]($DIFF_URL)" >> $GITHUB_STEP_SUMMARY
          ERROR_LOG=$(echo "$BISECT_OUTPUT" | awk '/first bad commit: first commit that fails/{flag=1; next} /Bisecting:/{flag=0} flag')
          echo "Error log:" >> $GITHUB_STEP_SUMMARY
          echo "$ERROR_LOG" >> $GITHUB_STEP_SUMMARY
        fi
        git bisect reset